### ISSUE TITLE
Can it work with Arduino framework?

### ISSUE THREAD

**Issue by zekageri** [espressif/esp-wolfssl#13]
I'm looking for a smaller footprint SSL lib for esp32 with the use of Arduino framework. Can i implement wolfssl if i'm not directly using IDF?

**Comment by AdityaHPatwardhan** [comment]
Hi @zekageri 
I have not used Arduino framework myself, so I am not sure I would be the right person to comment on this.

But just by looking at the support of [esp-tls](https://github.com/espressif/arduino-esp32/tree/00214d5c2a1c2b1904f2caf6f0d5ddfe952331ff/tools/sdk/esp32/include/esp-tls), and [mbedtls](https://github.com/espressif/arduino-esp32/tree/00214d5c2a1c2b1904f2caf6f0d5ddfe952331ff/tools/sdk/esp32/include/mbedtls)
I think it would be possible for you to include the [wolfssl](https://github.com/wolfSSL/wolfssl/tree/3f13b49fa318fbd3216d7da36d942e7c276d3413/wolfssl) and provide the wolfSSL source then I think it should be possible.

But please take a note of the updated [Licensing policy](https://github.com/espressif/esp-wolfssl#licensing) for esp-wolfssl.
Thanks,
Aditya

**Comment by zekageri** [comment]
Thank you for your comment. I found out that wolfssl has an Arduino port so I will implement that version to my project. And thank you for the note about the licensing.

**Comment by zekageri** [comment]
In case if anyone wondering, here is the [Arduino port](https://github.com/onelife/Arduino_wolfssl).
