### ISSUE TITLE
Does not compile with new gcc 11.2

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [espressif/esp-wolfssl#15]
I had to do a lot of patches of wolfssl to get it finally compiling again with newest idf,

and it seems like it crashes with unencrypted http_clients,
but does not with encrypted wss:// websocket_clients.

But then in fails to validate the server's certificate, although provided with 

```
    esp_websocket_client_config_t ws_cfg = {
        .uri = url.data(),
        .task_stack = 4*1024,
        .cert_pem = cloud_cert_pem.data(),
        .cert_len = cloud_cert_pem.size(),
    };
```

Is wolfssl somehow broken nowadays?

**Comment by 0xFEEDC0DE64** [comment]
https://github.com/wolfSSL/wolfssl/compare/master...0xFEEDC0DE64:fixes_with_new_idf

**Comment by AdityaHPatwardhan** [comment]
Hi @0xFEEDC0DE64 Sorry for the delayed reply, I missed the notification.
I shall look into this and see how I can run the latest version of the wolfssl with esp-idf.

**Comment by mahavirj** [comment]
@0xFEEDC0DE64 

> https://github.com/wolfSSL/wolfssl/compare/master...0xFEEDC0DE64:fixes_with_new_idf

I request that you raise this PR on upstream wolfssl repo, it will be useful in next release and uplevel here.

For now, we added some compiler flags to address issues with latest ESP-IDF development branch and some CI build tests too.

Please refer to https://github.com/espressif/esp-wolfssl/commit/470c02f5e3fcce3f9c7c98183dceb75a4bcc059b

Hope this helps!
