### ISSUE TITLE
how do I use this library to create a SHA1 Hasher?

### ISSUE THREAD

**Issue by zhy2020** [espressif/esp-wolfssl#18]
Hi, how do I use this library to implement the following python code?

from cryptography.hazmat.primitives import hashes
vin = bytes("5YJ3E1EA1KF000000", "UTF8")

# Create A SHA1 Hasher
digest = hashes.Hash(hashes.SHA1())

# Put VIN Into The Hasher
digest.update(vin)

# Set vinSHA To The Hex String Of The VIN Hash
vinSHA = digest.finalize().hex()

# Get The First 16 Characters
middleSection = vinSHA[0:16]
print(middleSection) # a6bab0d54ffaecf1

**Comment by gojimmypi** [comment]
Hi @zhy2020 there's a [wolfssl test](https://github.com/wolfSSL/wolfssl/tree/master/IDE/Espressif/ESP-IDF/examples/wolfssl_test) that includes SHA1 hashes. See the [int sha_test(void)](https://github.com/wolfSSL/wolfssl/blob/6cc5c1a42823099456202edc7868a6cca3553a0a/wolfcrypt/test/test.c#L2354) in [test.c](https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/test/test.c).

Let me know if that helps. If you encounter any problems, you can [open an issue there](https://github.com/wolfSSL/wolfssl/issues/new/choose) and I can help you further.

**Comment by zhy2020** [comment]
> Hi @zhy2020 there's a [wolfssl test](https://github.com/wolfSSL/wolfssl/tree/master/IDE/Espressif/ESP-IDF/examples/wolfssl_test) that includes SHA1 hashes. See the [int sha_test(void)](https://github.com/wolfSSL/wolfssl/blob/6cc5c1a42823099456202edc7868a6cca3553a0a/wolfcrypt/test/test.c#L2354) in [test.c](https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/test/test.c).
> 
> Let me know if that helps. If you encounter any problems, you can [open an issue there](https://github.com/wolfSSL/wolfssl/issues/new/choose) and I can help you further.

thanks.
