### ISSUE TITLE
ALPN protocol

### ISSUE THREAD

**Issue by xiruilin** [espressif/esp-wolfssl#2]
Is ALPN supported?
Thanks!

**Comment by AdityaHPatwardhan** [comment]
hi @xiruilin , and YES ,  ALPN is supported in esp-tls, for now only with mbedtls ssl stack, 
By default it is turned on with ` menuconfig -> Component config -> mbedtls -> Support ALPN ` , For wolfssl it is not yet provided in binary which will soon be provided!.

**Comment by xiruilin** [comment]
@AdityaHPatwardhan 
Got it, I mean at wolfssl, thanks!

**Comment by AdityaHPatwardhan** [comment]
@xiruilin, option to enable ALPN is now added in wolfSSL.and if there isn't anything else, you can go forward and close this issue. Thank You.

**Comment by xiruilin** [comment]
@AdityaHPatwardhan 
We will try it as soon as possible.
Thanks!

**Comment by xiruilin** [comment]
@AdityaHPatwardhan 
Everything works, including ALPN and HTTPS server.
Thanks!
