### ISSUE TITLE
will this be obsolete soon ? 

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-wolfssl#23]
seems we will be able to directly use wolf ? right ? 
https://components.espressif.com/components/wolfssl/wolfssl

**Comment by gojimmypi** [comment]
hi @diplfranzhoepfinger  - that's correct. The ESP Component Registry is definitely much easier to get started and has more recent  wolfSSL code. 

You can also download and use wolfSSL directly: see the [wolfssl/IDE/Espressif/ESP-IDF](https://github.com/wolfSSL/wolfssl/tree/master/IDE/Espressif/ESP-IDF)  and [wolfssl-examples/ESP32](https://github.com/wolfSSL/wolfssl-examples/tree/master/ESP32). The latest `CMakeLists.txt` is considerably more robust and easier to use. I have more improvements coming soon.

This is not a wolfSSL repo, so we don`t have permissions to update it. At some point, I need to coordinate with @igrr and @kumekay to either change ownership or transfer this repo. Sorry for any confusion.

I've opened https://github.com/espressif/esp-wolfssl/pull/22 to at least update the README file here to point users to the new [ESP Component Registry](https://components.espressif.com/components/wolfssl/wolfssl).

btw - I'm hosting a wolfSSL webinar this coming week on [Getting Started with wolfSSL on the Espressif ESP32](https://us02web.zoom.us/webinar/register/2616747721343/WN_8KamUT5OTXunGmxxQ_ZmsQ#/registration). Hope you can attend. :)
