### ISSUE TITLE
availability of esp-wolfssl for v3.3 

### ISSUE THREAD

**Issue by umer-ilyas** [espressif/esp-wolfssl#4]
Readme files says 
`To run the examples user must have installed ESP-IDF version v4.1 (minimum supported)`

is there any plan to release this for `v3.3 `
or Anybody is using this with esp-idf v3.3

**Comment by mahavirj** [comment]
@umer-ilyas 

No, there is no plan to support WolfSSL with IDF `v3.3` release. Reason primarily being it has dependency on refactoring that went into `esp-tls` component to support multiple TLS stacks, back-porting that feature is not very straight forward (also the fact that we typically backport only major bug-fixes for previous stable releases). If you would like you may use `WolfSSL` without `esp-tls` layer in IDF `v3.3` release (should be possible to use component with small changes in that release).

**Comment by mahavirj** [comment]
I will go ahead and close this issue. Please feel free to reopen if you have any questions or face any issues.
