### ISSUE TITLE
Component esp-wolfssl only supports targets: esp32;esp8266

### ISSUE THREAD

**Issue by SinglWolf** [espressif/esp-wolfssl#8]
Good day!
The official documentation of esp32-S2 says how to use the library.
![2021-05-06_04-47-26](https://user-images.githubusercontent.com/32172969/117223437-1a1d0880-ae27-11eb-9340-b4280ce2f585.png)

When compiling the project, I get this message.
![2021-05-06_04-48-10](https://user-images.githubusercontent.com/32172969/117223456-25703400-ae27-11eb-8e3e-ee32d795d860.png)

When will esp32-S2 be supported?

**Comment by mahavirj** [comment]
@SinglWolf 

We have pushed some updates to this repository, if you pull latest changes then ESP32-S2 and ESP32-C3 will be supported as well. However please take a note about licensing per https://github.com/espressif/esp-wolfssl#licensing

**Comment by mahavirj** [comment]
@SinglWolf 

We have tested updated changes for ESP32-S2. I will resolve this issue. Please feel free to re-open if you still have any questions.

**Comment by ghenry** [comment]
Where do you put the wolfssl main sources now?
